/**
 * Torus.h - Simplified torus geometry primitive
 *
 * A torus is a surface of revolution generated by revolving a circle
 * around an axis coplanar with the circle. Also known as a donut shape.
 */
#pragma once

#include<hgl/math/Vector.h>
#include<hgl/math/geometry/AABB.h>
#include<numbers>
#include<cmath>

namespace hgl::math
{
    /**
     * Torus - Circular cross-section torus
     *
     * Geometric definition:
     * - Center: Center of the torus
     * - Axis: Direction perpendicular to major circle plane (normalized)
     * - Major radius (R): Distance from torus center to tube center
     * - Minor radius (r): Radius of tube cross-section
     *
     * Mathematical equation:
     * For a point (x,y,z) on the torus:
     * (sqrt(x² + y²) - R)² + z² = r²
     *
     * Properties:
     * - Volume = 2π²Rr²
     * - Surface area = 4π²Rr
     * - Must have R > r for a valid torus
     *
     * Common uses:
     * - Donut shapes
     * - Pipe bends
     * - Decorative objects
     */
    class Torus
    {
        Vector3f center;         // Torus center
        Vector3f axis;           // Axis direction (normalized)
        float major_radius;      // Major radius R (to tube center)
        float minor_radius;      // Minor radius r (tube thickness)

    public:

        /**
         * Default constructor
         * Creates a torus at origin, Y-axis aligned, R=1.0, r=0.3
         */
        Torus()
            : center(0, 0, 0), axis(0, 1, 0), major_radius(1.0f), minor_radius(0.3f)
        {
        }

        /**
         * Parameterized constructor
         * @param c Center position
         * @param a Axis direction (will be normalized)
         * @param major_r Major radius (must be > minor_r)
         * @param minor_r Minor radius (must be > 0)
         */
        Torus(const Vector3f& c, const Vector3f& a, float major_r, float minor_r)
        {
            Set(c, a, major_r, minor_r);
        }

        /**
         * Set torus parameters
         * @param c Center position
         * @param a Axis direction (will be normalized)
         * @param major_r Major radius (must be > minor_r)
         * @param minor_r Minor radius (must be > 0)
         */
        void Set(const Vector3f& c, const Vector3f& a, float major_r, float minor_r)
        {
            center = c;
            axis = Normalized(a);
            major_radius = major_r;
            minor_radius = minor_r;
        }

        /** Get torus center */
        const Vector3f& GetCenter() const { return center; }

        /** Get axis direction */
        const Vector3f& GetAxis() const { return axis; }

        /** Get major radius R */
        float GetMajorRadius() const { return major_radius; }

        /** Get minor radius r */
        float GetMinorRadius() const { return minor_radius; }

        /**
         * Calculate torus volume
         * Formula: V = 2π²Rr²
         * @return Volume
         */
        float GetVolume() const
        {
            constexpr float pi_squared = std::numbers::pi_v<float> * std::numbers::pi_v<float>;
            return 2.0f * pi_squared * major_radius * minor_radius * minor_radius;
        }

        /**
         * Calculate torus surface area
         * Formula: S = 4π²Rr
         * @return Surface area
         */
        float GetSurfaceArea() const
        {
            constexpr float pi_squared = std::numbers::pi_v<float> * std::numbers::pi_v<float>;
            return 4.0f * pi_squared * major_radius * minor_radius;
        }

        /**
         * Test if point is inside torus (solid)
         *
         * Algorithm:
         * 1. Project point onto major plane
         * 2. Calculate plane distance (horizontal)
         * 3. Calculate axis component (height)
         * 4. Find distance to tube centerline
         * 5. Check if <= minor radius
         *
         * @param point Point to test
         * @return true if inside or on surface
         */
        bool ContainsPoint(const Vector3f& point) const
        {
            Vector3f to_point = point - center;

            // Height component along axis
            float axis_component = Dot(to_point, axis);

            // Projection onto major plane
            Vector3f plane_projection = to_point - axis * axis_component;
            float plane_distance = Length(plane_projection);

            // Distance to tube centerline
            float distance_to_tube_center = std::sqrt(
                (plane_distance - major_radius) * (plane_distance - major_radius) +
                axis_component * axis_component
            );

            return distance_to_tube_center <= minor_radius;
        }

        /**
         * Find closest point on torus surface
         * @param point Point in space
         * @return Closest point on surface
         */
        Vector3f ClosestPoint(const Vector3f& point) const
        {
            Vector3f to_point = point - center;

            // Project onto major plane
            float axis_component = Dot(to_point, axis);
            Vector3f plane_projection = to_point - axis * axis_component;
            float plane_distance = Length(plane_projection);

            // Find point on major circle (tube centerline)
            Vector3f tube_center_direction;
            if (plane_distance > 0.0001f)
            {
                tube_center_direction = plane_projection / plane_distance;
            }
            else
            {
                // Point on axis - choose arbitrary direction
                if (std::abs(axis.x) < 0.9f)
                    tube_center_direction = Cross(axis, Vector3f(1, 0, 0));
                else
                    tube_center_direction = Cross(axis, Vector3f(0, 1, 0));
                tube_center_direction = glm::normalize(tube_center_direction);
            }

            Vector3f tube_center = center + tube_center_direction * major_radius;

            // Project from tube center to surface
            Vector3f to_surface = point - tube_center;
            float dist_to_center = Length(to_surface);

            if (dist_to_center > 0.0001f)
            {
                return tube_center + to_surface * (minor_radius / dist_to_center);
            }
            else
            {
                // Point exactly at tube center - return point on surface
                return tube_center + tube_center_direction * minor_radius;
            }
        }

        /**
         * Calculate distance from point to torus surface
         * @param point Point in space
         * @return Distance to surface (0 if inside)
         */
        float DistanceToPoint(const Vector3f& point) const
        {
            Vector3f to_point = point - center;

            float axis_component = Dot(to_point, axis);
            Vector3f plane_projection = to_point - axis * axis_component;
            float plane_distance = Length(plane_projection);

            float distance_to_tube_center = std::sqrt(
                (plane_distance - major_radius) * (plane_distance - major_radius) +
                axis_component * axis_component
            );

            float dist = distance_to_tube_center - minor_radius;
            return dist > 0.0f ? dist : 0.0f;
        }

        /**
         * Get axis-aligned bounding box
         * @return AABB containing this torus
         */
        AABB GetBoundingBox() const
        {
            // Torus extends major_radius + minor_radius in plane directions
            // and minor_radius along axis
            float max_planar = major_radius + minor_radius;

            // Conservative bbox accounting for arbitrary axis orientation
            Vector3f extent_planar(max_planar, max_planar, max_planar);
            Vector3f extent_axial = glm::abs(axis) * minor_radius;
            Vector3f total_extent = extent_planar + extent_axial;

            AABB box;
            box.SetMinMax(center - total_extent, center + total_extent);
            return box;
        }

    };//class Torus

}//namespace hgl::math
